version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env.example
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: studytracker
      POSTGRES_PASSWORD: studytracker
      POSTGRES_DB: studytracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
